### ISSUE TITLE
About Clothing1M dataset

### ISSUE THREAD

**Issue by ousinkou** [KentoNishi/Augmentation-for-LNL#1]
Where can I download Clothing1M dataset for testing?

**Comment by KentoNishi** [comment]
Thanks for asking!

Information about downloading the dataset is included in the README of the original paper that introduced the dataset.

https://github.com/Cysu/noisy_label#clothing1m-experiments

> Download the dataset. Please contact tong.xiao.work[at]gmail[dot]com to get the download link.

Alternatively, you can try this from FloydHub (unverified, just found on google):
https://www.floydhub.com/lukasmyth/datasets/clothing1m

**Comment by ousinkou** [comment]
Great! Thank you.
