### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [KentoNishi/Augmentation-for-LNL#6]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set).

Thanks!

**Comment by KentoNishi** [comment]
So sorry for the late response! I didn't realize there was a new issue.

1. If you mean tabular data as in non-vision data, I doubt DivideMix would work out if the box. This work and previous works only investigate label noise in the domain of CV classification problems. To handle tabular data, you probably need to find a different base method. That being said, once you find an adequate method for tabular label noise, the principles of strong and weak augmentations *may* improve performance.
2. Yes. You could turn off random shuffling in the dataloader, compute all individual per-sample losses, fit the gmm, then log IDs which satisfy your noisiness threshold.

I hope these answer your questions!
